model_type: arima
version: v3
db_path: data/forecast_results.db
target_col: temperature_2m

start_date: "2023-01-01"
end_date: "2024-12-01"

arima_params:
  p_range:
    min: 6
    max: 8
  d_range:
    min: 1
    max: 2
  q_range:
    min: 4
    max: 6
