model_type: "ml"
version: "v5"
db_path: "data/forecast_results.db"
target_col: "temperature_2m"
exog_cols:
  - relative_humidity_2m
  - wind_speed_10m
  - cloud_cover

start_date: "2022-01-01"
end_date: "2024-12-01"

ml_model: "rf" # Options: "lr", "rf"

ml_params:
  n_estimators: [50, 100]
  max_depth: [5, 10]
