model_type: "sarima"
version: "v3"
db_path: "data/forecast_results.db"
target_col: "temperature_2m"

start_date: "2024-06-01"
end_date: "2024-08-01"

sarima_params:
  p_range:
    min: 1
    max: 4
  d_range:
    min: 1
    max: 2
  q_range:
    min: 1
    max: 3
  sp_range:
    min: 0
    max: 3
  sd_range:
    min: 1
    max: 2
  sq_range:
    min: 0
    max: 3
  seasonal_period: 8
